version: '3'
services:
  actions:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"  # Map container port 5055 to host port 5055
    volumes:
      - .:/app  # Mount the current directory into the container
    networks:
      - rasa_networks
  rasa:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"  # Map container port 5005 to host port 5005
    volumes:
      - .:/app  # Mount the current directory into the container
    networks:
      - rasa_networks

networks:
  rasa_networks:
    name: rasa_networks
    driver: bridge

